### ISSUE TITLE
青龙设置定时运行会报错

### ISSUE THREAD

**Issue by cnqv** [x2rr/ProxyWhiteListUpdater#1]
![1](https://github.com/user-attachments/assets/77aa855e-93c4-48fe-b955-ebd93799d9c0)
手动运行有时正常，有时也同样会报错，请问大佬什么原因？

**Comment by x2rr** [comment]
> ![1](https://private-user-images.githubusercontent.com/21341839/352761700-77aa855e-93c4-48fe-b955-ebd93799d9c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMzU5MzIsIm5iZiI6MTcyMjEzNTYzMiwicGF0aCI6Ii8yMTM0MTgzOS8zNTI3NjE3MDAtNzdhYTg1NWUtOTNjNC00OGZlLWI5NTUtZWJkOTM3OTlkOWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDAzMDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MGYzYzE0YzdlNWEyOGI4MTUzZDk2Nzc3NmY1OGU2MzBmOGI0YWRlZmU1MjlhMDk1OWExY2U5OWYyYzdmNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gojYV6wxblm_LPWIy608R6-6dt3NwRbCKBjC4fEFNLY) 手动运行有时正常，有时也同样会报错，请问大佬什么原因？

本机网络问题
